makro_ecommerce_admin:
  build: web/
  tty: true
  ports:
    - "8054:80"
  volumes:
    - ../:/var/www/html
  environment:
    ENVIRONMENT: develop
  external_links:
    - makro-mongo:mongo
    - makro-bss-redis:redis

    - makro-member-api:makro-member-api
    - makro-category-api:makro-category-api
    - makro-attribute-api:makro-attribute-api
    - makro-product2-api:makro-product2-api
    - makro-content-api:makro-content-api
    - makro-tag-api:makro-tag-api
    - makro-permission-api:makro-permission-api
    - makro-campaign-api:makro-campaign-api
    - makro-product-int:makro-product-int
    - makro-order-api:makro-order-api
    - makro-config-ms-api:makro-config-ms-api
    - makro-store-ms-api:makro-store-ms-api
    - makro-coupon-api:makro-coupon-api

   # - makro-member-api:makro-member-api
  # external_links:
  #   - makro_banner_api:alpha-api-makro-banner.eggdigital.com
  #   - makro_member_api:alpha-api-makro-member.eggdigital.com
  #   - makro_category_api:alpha-api-makro-category.eggdigital.com
  #   - makro_attribute_api:alpha-api-makro-attribute.eggdigital.com
  #   - makro_product2_api:alpha-api-makro-product2.eggdigital.com
  #   - makro_content_api:alpha-api-makro-content.eggdigital.com
  #   - makro_product2_api:alpha-api-makro-product2.eggdigital.com
  container_name: makro_ecommerce_admin

